const DEFAULT_INTENSITY = 40;
const MIN_INTENSITY = 0;
const DEFAULT_SPEED_FOR_MAX_BLUR = 1500;
const MIN_SPEED_FOR_MAX_BLUR = 1;
const DEFAULT_SAMPLES = 32;
const MIN_SAMPLES = 4;
const MAX_SAMPLES = 64;
const DEFAULT_MOTION_BLUR_ENABLED = true;
const DEFAULT_MOTION_BLUR_LIVE = false;

export {
  DEFAULT_INTENSITY,
  MIN_INTENSITY,
  DEFAULT_SPEED_FOR_MAX_BLUR,
  MIN_SPEED_FOR_MAX_BLUR,
  DEFAULT_SAMPLES,
  MIN_SAMPLES,
  MAX_SAMPLES,
  DEFAULT_MOTION_BLUR_ENABLED,
  DEFAULT_MOTION_BLUR_LIVE,
};
