const AUTH_BUTTON_VARIANTS = {
  PRIMARY: 'primary',
  SECONDARY: 'secondary',
} as const;

const AUTH_SHEET_LAYOUT = {
  PADDING: 24,
  PADDING_BOTTOM: 30,
  APP_ICON_SIZE: 70,
  APP_ICON_RADIUS: 16,
  TITLE_MARGIN_TOP: 18,
  DESCRIPTION_MARGIN_TOP: 6,
  ACTIONS_MARGIN_TOP: 36,
  ACTIONS_INSET: 20,
  ACTION_GAP: 12,
  BUTTON_HEIGHT: 56,
  BUTTON_ICON_GAP: 8,
  APPLE_ICON_SIZE: 20,
  GOOGLE_ICON_SIZE: 17,
  ENVELOPE_ICON_SIZE: 22,
} as const;

export { AUTH_BUTTON_VARIANTS, AUTH_SHEET_LAYOUT };
