const COMPONENT_NAMES = {
  CHAT_SCREEN: 'ChatScreen',
  HEADER_BAR: 'HeaderBar',
  ICON_BUTTON: 'IconButton',
  UPGRADE_BUTTON: 'UpgradeButton',
  SUGGESTION_LIST: 'SuggestionList',
  SUGGESTION_ITEM: 'SuggestionItem',
  COMPOSER: 'Composer',
  GLASS_PRESSABLE: 'GlassPressable',
  GLASS_SURFACE: 'GlassSurface',
  DRAWER: 'Drawer',
  SIDEBAR: 'Sidebar',
  SIDEBAR_ROW: 'SidebarRow',
  MENU_BUTTON: 'MenuButton',
  NEW_CHAT_BUTTON: 'NewChatButton',
  BOTTOM_SHEET: 'BottomSheet',
  AUTH_SHEET: 'AuthSheet',
  AUTH_BUTTON: 'AuthButton',
  MENU_ICON: 'MenuIcon',
  DASHED_CHAT_ICON: 'DashedChatIcon',
  SPARKLE_ICON: 'SparkleIcon',
  WAVEFORM_ICON: 'WaveformIcon',
  IMAGE_ICON: 'ImageIcon',
  PENCIL_ICON: 'PencilIcon',
  PLUS_ICON: 'PlusIcon',
  MICROPHONE_ICON: 'MicrophoneIcon',
  APPLE_ICON: 'AppleIcon',
  GOOGLE_ICON: 'GoogleIcon',
  CHATGPT_ICON: 'ChatGPTIcon',
  ENVELOPE_ICON: 'EnvelopeIcon',
  SEARCH_ICON: 'SearchIcon',
  BRUSH_ICON: 'BrushIcon',
  BOOKS_ICON: 'BooksIcon',
  FOLDER_ICON: 'FolderIcon',
  HEART_BADGE_ICON: 'HeartBadgeIcon',
  CLOCK_ICON: 'ClockIcon',
  SHAPES_ICON: 'ShapesIcon',
  CHAT_BUBBLE_ICON: 'ChatBubbleIcon',
  COMPOSE_ICON: 'ComposeIcon',
  GEAR_ICON: 'GearIcon',
} as const;

export { COMPONENT_NAMES };
