const BORDER_WIDTH = 1;

const HEADER_LAYOUT = {
  HEIGHT: 44,
  PADDING_HORIZONTAL: 20,
  GAP: 12,
} as const;

const ICON_BUTTON_LAYOUT = {
  SIZE: 44,
  ICON_SIZE: 24,
} as const;

const UPGRADE_BUTTON_LAYOUT = {
  HEIGHT: 44,
  PADDING_LEFT: 16,
  PADDING_RIGHT: 15,
  GAP: 5,
  ICON_SIZE: 20,
} as const;

const SUGGESTION_LAYOUT = {
  ROW_HEIGHT: 47,
  PADDING_HORIZONTAL: 24,
  ICON_SIZE: 24,
  GAP: 12,
  MARGIN_BOTTOM: 12,
} as const;

const COMPOSER_LAYOUT = {
  HEIGHT: 48,
  MARGIN_HORIZONTAL: 34,
  PADDING: 7,
  ACTION_SIZE: 32,
  ACTION_HIT_SLOP: 6,
  ACTION_GAP: 16,
  ICON_SIZE: 24,
  VOICE_ICON_SIZE: 22,
  INPUT_MARGIN_HORIZONTAL: 9,
  INPUT_PADDING_BOTTOM: 2,
  MIN_BOTTOM_INSET: 12,
  KEYBOARD_GAP: 8,
} as const;

const SIDEBAR_LAYOUT = {
  PADDING_HORIZONTAL: 24,
  CONTENT_PADDING_TOP: 12,
  ROW_HEIGHT: 48,
  ROW_INSET: 12,
  ROW_GAP: 12,
  ICON_SIZE: 24,
  SECTION_MARGIN_TOP: 12,
  FOOTER_HEIGHT: 48,
  FOOTER_PADDING_LEFT: 30,
  FOOTER_PADDING_RIGHT: 24,
  NEW_CHAT_PADDING_LEFT: 22,
  NEW_CHAT_PADDING_RIGHT: 24,
  NEW_CHAT_GAP: 10,
  MIN_BOTTOM_INSET: 12,
} as const;

export {
  BORDER_WIDTH,
  HEADER_LAYOUT,
  ICON_BUTTON_LAYOUT,
  UPGRADE_BUTTON_LAYOUT,
  SUGGESTION_LAYOUT,
  COMPOSER_LAYOUT,
  SIDEBAR_LAYOUT,
};
